src/blur.cpp, src/blur.h, src/blur.kcfg, src/kcm/blur_config.ui
This PR adds a fix for artifacts caused by some windows not being fully repainted when using a translucent color scheme.
https://github.com/taj-ny/kwin-effects-forceblur/assets/79316397/c3712289-4d59-4578-8f1d-ad25a0a9c66f
=> develop: add option to mark windows as translucent

src/blur.cpp, src/blur.h, src/blur.kcfg, src/blur.qrc, src/kcm/blur_config.ui, src/shaders/texture.frag, src/shaders/texture_core.frag
Fake blur works by drawing an already blurred image behind the window, which results in lower GPU load as KWin doesn't have to blur anything and it also doesn't have to paint everything behind the window.
Currently, the image must be blurred manually in an image editor. In the future, that will be done automatically when the effect is loaded.
https://github.com/taj-ny/kwin-effects-forceblur/assets/79316397/492ea9b9-f3eb-457b-ab4a-28f2bfd43cea
Also works with multiple screens, as long as the wallpapers and resolutions are the same.
Closes #41.
=> add fake blur

src/blur.cpp, src/blur.h
This fixes an issue where the blur region would sometimes disappear for a few frames when the window is transformed. It's caused by the force blur role being removed too early. This issue also occurs with the stock blur effect.
=> blur: add workaround for blur flickering when transforming windows

README.md, flake.lock, src/blur.cpp, src/blur.h, src/blur.kcfg, src/blur.qrc, src/kcm/blur_config.ui, src/shaders/roundedcorners.frag, src/shaders/roundedcorners_core.frag, src/shaders/texture.frag, src/shaders/texture_core.frag, src/utils.h
This is a rewrite of the rounded corners implementation, which has much better-looking corners. There's probably a better way to do it, but for now that's the simplest and most efficient way of doing it that I can implement myself.
The corner radiuses are also now decimal values.
The pictures were made in the worst possible situation: maximum blur strength with the corner being on a darker surface right next to a bright one.
No antialiasing:
0,5 antialiasing:
17px blur radius with 1 antialiasing
Couldn't get it to match perfectly, but it's definitely better than before.
14,75px blur radius with 0,5 antialiasing
Looks perfect.
=> blur/rounded-corners: rewrite

CMakeLists.txt, README.md, flake.lock, flake.nix, package.nix, src/blur.cpp, src/kcm/CMakeLists.txt, src/metadata.json
I'm not changing the effect ID as that would disable it for everyone, so it'll remain ``forceblur`` until 2.0.
=> rename project to KWin Better Blur (kwin-better-blur)

src/blur.cpp
decorationInnerRect [was removed](https://invent.kde.org/plasma/kwin/-/commit/8542c2003014930c842f893cff956a32f92b4772)
Haven't tested with 6.1 but I believe it should be backwards-compatible
=> Fix for kwin's master branch

src/blur.cpp, src/blur.h
This PR fixes the following issues related to window overlap detection when **Use real blur for windows that are in front of other windows** is enabled:
- The invisible xwaylandvideobridge window located in the top-left corner was not ignored
- Minimized windows were not ignored
- KWin would sometimes crash when closing a window, possibly caused by the EffectWindow being deleted
- Windows on other activities were not ignored
=> blur/fake-blur: improve window overlap detection

README.md, docs/configuration.md, src/blur.cpp, src/blur.h, src/kcm/blur_config.ui, tools/plasma-nested.sh
This fixes the following issues: 
- Fake blur doesn't work on screens other than the primary one
- The image isn't scaled properly
- The image doesn't change when the wallpaper does
- The image may be black if a window had requested blur before the wallpaper appeared
- Fake blur doesn't work properly on X11 with multiple
=> blur/fake-blur: fix various issues when using the wallpaper as the image

src/blur.cpp
On Xorg, the effects need support for OpenGL blits, but on Wayland, the screen texture can be used instead
https://invent.kde.org/plasma/kwin/-/commit/b35edf8d301e2073f242bc88c121dd4fca1b1beb
=> correct support check

src/blur.cpp
Using glBindTexture instead of GLTexture::bind() caused the texture's filter and wrap mode to not be applied, which in turn resulted in an outline inside the window.
=> blur: fix upsample texture binding

src/blur.cpp
If a window had real blur but then switched to fake blur, the textures used for real blur would still be kept in memory, even though they may never be used again.
=> blur: free the window's blur textures if it has fake blur

src/blur.cpp
f838534ba6354fe95dfbc8f179a5af03e54095f5 fixed it on X11 and broke it on Wayland.
=> force-blur: fix blur region for x11 windows with csd on wayland

src/blur.cpp, src/blur.h, src/shaders/texture.glsl, src/shaders/texture_core.glsl
=> static-blur: remove unnecessary scale uniform from the shader

src/blur.cpp
For very small windows, the width and/or height of the last blur texture may be 0. Creation of and/or usage of invalid textures to create framebuffers appears to cause performance issues.
At the highest blur strength, the minimum window size would be 16x16.
=> blur: ensure blur textures are always at least 1x1 in size

src/blur.cpp
Once window rules are finally implemented, the output of shouldForceBlur could only be evaluated once and then cached.
=> force-blur: ignore xwaylandvideobridge and spectacle's overlays

README.md
Looks like the current building instructions are way too difficult to understand for some people, even with the big purple note, so I tried to simplify them, at the cost of duplication.
Maybe I should just make a script for that.
=> readme: simplify building instructions

README.md
On Kubuntu 25.04, the package `libkdecorations2-dev` no longer has an installation candidate. It is replaced by the package `libkdecorations3-dev`. Installing this package satisfies the build requirements and the effect works without any encountered problems so far.
Terminal output after installing build dependencies from the README.md
```
sudo apt install git cmake g++ extra-cmake-modules qt6-tools-dev kwin-dev libkf6configwidgets-dev gettext libkf6crash-dev libkf6globalaccel-dev libkf6kio-dev libkf6service-dev libkf6notifications-dev libkf6kcmutils-dev libkdecorations2-dev libxcb-composite0-dev libxcb-randr0-dev libxcb-shm0-dev
Package libkdecorations2-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only …
```
=> Replace libkdecorations2-dev with libkdecorations3-dev

CMakeLists.txt, src/blur.cpp
> It's not guaranteed that the driver fills them with sane values, if we don't clear them, then areas of the textures that aren't immediately painted to (like when the window starts up partially off-screen) can contain random noise and affect the final result.
https://invent.kde.org/plasma/kwin/-/commit/b81a8635dd40380bbd4e39d4584221caca1abd8f
=> blur: clear textures after allocation

.github/workflows/fedora-42.yml, README.md
=> workflows: remove fedora 40, add 42

README.md
This effect has been built in my copr for about a year, since Fedora 40. Currently the package "just works", with the only limiting factors being:
1. Often needs kwin/plasmashell to be restarted after upgrades
2. Limited free time on my end, often delaying updates
You can check the spec file [here](https://download.copr.fedorainfracloud.org/results/hazel-bunny/ricing/fedora-rawhide-aarch64/09247243-kwin-effects-forceblur/kwin-effects-forceblur.spec) and also try other packages in my copr repository to make sure you and your users could trust my COPR repository.
=> Add COPR Repository for Fedora

src/kcm/blur_config.cpp, src/kcm/blur_config.h, src/kcm/blur_config.ui, src/settings.cpp
When splitting user specified window classes by line, ignore empty lines. This prevents *unintentionally* matching windows with empty resource class or resource name.  
[To match empty classes and names, use `$blank` as suggested.](https://github.com/taj-ny/kwin-effects-forceblur/pull/226#issuecomment-3077702824)
<details>
<summary>Show resolved</summary>
> When splitting user specified window classes by line, ignore single empty lines. This prevents *unintentionally* matching windows with empty resource class or resource name.
</details>
Fixes #193, fixes #219, fixes #104
A better solution would be to use something like a list with editable items/rows instead of a plain text box, there would be no ambiguities about whether an item should be kept or skipped, but it would greatly increase …
=> Ignore empty lines in the specified window classes
